name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./CI-CD-Pipeline-Component
      - name: Run tests
        run: npm run build
             npm test
        working-directory: ./CI-CD-Pipeline-Component
